name: Merge automatically
on:
  pull_request:
    types:
      - labeled
jobs:
  merge-into-master:
    runs-on: ubuntu-latest
    steps:
      - name: Merge into master
        uses: 'pascalgn/automerge-action@v0.7.4'
        if: github.base_ref == 'master'
        env:
          # This is a personal access token, it should be updated if the user's account is no longer available
          GITHUB_TOKEN: '${{ secrets.MERGE_TOKEN }}'
          MERGE_LABELS: 'MERGE'
          MERGE_METHOD: 'merge'
          MERGE_DELETE_BRANCH: 'true'
          UPDATE_METHOD: 'rebase'
